language: php

php:
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=8.2.0
  - LARAVEL_VERSION=8.1.0
  - LARAVEL_VERSION=8.0.1
  - LARAVEL_VERSION=dev-master
  - LARAVEL_VERSION=
matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - vendor/bin/phpunit

after_script:
#  - php vendor/bin/php-coveralls -v
